#!/bin/bash
if command -v python3 &> /dev/null; then
    python3 server/server.py $@
elif command -v python &> /dev/null; then
    python server/server.py $@
else
    echo "Python is not installed. Please install Python 3."
    exit 1
fi
