#!/bin/bash
if command -v python3 &> /dev/null; then
    python3 client/client.py $@
elif command -v python &> /dev/null; then
    python client/client.py $@
else
    echo "Python is not installed. Please install Python 3."
    exit 1
fi
